Repository asciiflix/webclient, pull requests merged in 2021-07, with the labels that each got.

#60 Some CSS and Text Fixes
  src/Common/TitleBarMenu/TitleBarMenu.css
  src/Common/TitleBarMenu/TitleBarMenu.tsx
  src/Components/Login/UserLogin.css
  src/Components/Register/UserRegistration.css
  src/Components/Register/UserRegistration.tsx
  src/Components/Upload/UploadGIF.css
  src/Components/Upload/UploadGIF.tsx
  src/Components/VideoEdit/VideoEdit.tsx
Labels: bug

#62 Bugfix/user url
  src/Common/TitleBarMenu/TitleBarMenu.tsx
Labels: bug

#65 Feature/thumbnail
  src/Common/VideoPreview/VideoPreview.css
  src/Common/VideoPreview/VideoPreview.tsx
  src/Components/VideoPlayer/VideoPlayer.tsx
Labels: enhancement

#66 Fixed Upload
  src/Common/TitleBarMenu/TitleBarMenu.tsx
  src/Components/Upload/UploadGIF.tsx
  src/Pages/UserProfilePage/UserProfilePage.tsx
Labels: bug

#67 Added dynamic dates
  src/Common/Helper/Date.tsx
  src/Components/Comments/Comments.tsx
  src/Components/VideoInfo/VideoInfo.tsx
Labels: enhancement

#68 Fixed nowrap
  src/Components/Comments/Comments.css
Labels: bug

#75 Bugfix/bugfixes
  src/App.tsx
  src/Common/Helper/UserNameShorter.tsx
  src/Common/UserPreview/UserPreview.css
  src/Common/UserPreview/UserPreview.tsx
  src/Common/VideoPreview/VideoPreview.css
  src/Common/VideoPreview/VideoPreview.tsx
  src/Components/Search/Search.css
  src/Components/Search/Search.tsx
  src/Components/Settings/Settings.css
  src/Components/Settings/Settings.tsx
  src/Components/UserProfile/UserProfile.css
  src/Components/UserProfile/UserProfile.tsx
  src/Components/Verify/Verify.css
  src/Components/Verify/Verify.tsx
  src/Components/VideoPlayer/VideoPlayer.tsx
  src/Pages/SearchPage/SearchPage.css
  src/Pages/SearchPage/SearchPage.tsx
  src/Pages/UserProfilePage/UserProfilePage.css
  src/Pages/UserProfilePage/UserProfilePage.tsx
  src/Pages/VerifyPage/VerifyPage.tsx
Labels: bug, enhancement
